language: objective-c
# xcode_project: Pangu.Objective-C.xcodeproj
# xcode_scheme: Pangu.Objective-CTests
# xcode_sdk: iphonesimulator
script:
  - xctool -project Pangu.Objective-C.xcodeproj -scheme Pangu.Objective-CTests build test -sdk iphonesimulator GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
  - bash <(curl -s https://codecov.io/bash)